esphome:
  name: esphome-web-ebe1f0
  friendly_name: ESPHome32
  min_version: 2025.4.0
external_components:
  #- source:
  #    type: local
  #    path: components
  #  components: [ap3216]
  - source: github://10-thousand/esphome-AP3216@main
    components: [ap3216]
esp32:
  board: esp32dev
  framework:
    type: arduino
    
# Enable Home Assistant API
api:
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH

web_server:
  port: 80

i2c:
  sda: GPIO21
  scl: GPIO22

sensor:
  - platform: ap3216
    mode: ALS_PS
    operating_mode: VALUE
    ambient_light: "Ambient light"
    ps_counts: "Proximity"
    infrared_counts: "Infrared"
    ir_data: "Ir data"
    is_near: "is_near"
    
    address: 0x23
    update_interval: 60s


logger:
  level: VERBOSE
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR
